window.BINGO_THEMES = window.BINGO_THEMES || {};
window.BINGO_THEMES["TTRPG"] = [
    "Natural 20!", "Natural 1...", "Are you sure you want to do that?", "I have Darkvision!", "How do you want to do this?",
    "Rules lawyer cites the handbook", "Murderhobo attacks the quest-giver", "The Bard flirts with a monster", "The Rogue steals from the party", "The Paladin won't stop talking about their oath",
    "Wizard runs out of spell slots", "Fighting a door for 20 minutes", "Cocked die (doesn't count)", "Die falls off the table", "Rolling a 1 on a damage die",
    "Rolling max damage", "DM rolls behind the screen and sighs", "Someone forgot their character sheet", "Someone forgot their dice", "Snacks are louder than the roleplay",
    "Bad accent that changes mid-session", "Using a spell in a way the DM didn't expect", "Spending an hour planning, then ignoring the plan", "Mimic!", "Hidden trap found the hard way",
    "Looting a body before the fight is over", "Argue over a 5ft square", "Cleric forgets to heal", "Barbarian is too angry to die", "Warlock mentions their Patron again",
    "Ranger's pet does more damage than the Ranger", "Finding a magic item that is useless", "Naming an NPC 'Bob' because the DM panicked", "Shopkeeper is secretly a level 20 Wizard", "Party splits up",
    "I roll for Insight", "Critical fail on a Stealth check", "Potion of Healing is used too late", "Taking a long rest in a dangerous dungeon", "Initiative is rolled, everyone groans",
    "Someone does the math wrong", "Tabletop miniatures are actually LEGOs or coins", "DM describes a very specific smell", "I'd like to rage", "Fireball in a small room",
    "Wild Shape into something useless", "Someone falls asleep IRL", "Phone distraction during combat", "Over-explaining a simple action", "Critical hit on a lowly minion",
    "The 'Chosen One' dies in the first session", "Session starts an hour late", "Someone brings up a rule from a different edition", "The 'Diplomacy' check that shouldn't work", "Failing a save with a +10 modifier",
    "DM's 'Evil Laugh'", "NPC has a funny name that becomes a meme", "Accidentally starting a tavern brawl", "Ignoring the obvious plot hook", "The 'Bag of Holding' physics debate",
    "Rolling for something completely unnecessary", "DM forgets an NPC's name", "Player tries to negotiate with a mindless beast", "Critically successful 'Identify' on a mundane rock", "The party gets lost in a 10ft hallway",
    "Someone spills a drink on the table", "The 'What did I miss?' from a late arrival", "Using 'Prestidigitation' for everything", "A player reads the monster's stat block", "The 'Can I add my proficiency?' question",
    "Counterspell war", "The Monk runs across water just because they can", "Failing to open an unlocked door", "The Druid tries to talk to a plant", "Someone mentions the 'Meta-game'",
    "The Cleric goes 'Battle Mode' and ignores the dying party", "Finding a secret door by accident", "The 'How much does this weigh?' debate", "Buying a thousand feet of rope", "The DM's 'I'll allow it' face",
    "A Nat 20 on a check that doesn't matter", "The Sorcerer accidentally teleports into a wall", "Rogue hides in plain sight", "A Nat 1 on an Initiative roll", "Finding out the villain was right",
    "The 'Wait, I have a bonus action' realization", "Someone's familiar dies immediately", "The party spends all their gold on a pet", "A lore dump that no one takes notes on", "The 'Can we take a short rest?' plea",
    "Total Party Kill (TPK) looms", "The DM fudges a roll (suspiciously)", "A player tries to invent gunpowder", "A convoluted plan that works", "A simple plan that fails miserably",
    "The 'Wait, how do I calculate that?'", "Someone rolls 3D6 for something that takes a D20", "The dice tray is full", "Someone's character voice is just their normal voice but louder", "The 'I loot the room' instinct",
    "A puzzle meant for children takes 45 minutes", "The 'I check for traps' every 5 feet", "The DM describes the scenery for 5 minutes", "The 'I know a guy' background feature", "A Nat 20 on a death save",
    "The party adopts a goblin", "The 'It's what my character would do' excuse", "Someone brings a very fancy set of metal dice", "The sound of 20 dice being rolled at once", "A player explains their backstory for the third time",
    "The 'Session Zero' was ignored", "The 'End of the Session' cliffhanger", "The 'We didn't prepare for this' DM panic", "A player tries to tame a dragon", "The 'I search for secret buttons'",
    "The party spends 30 minutes buying basic supplies", "A Nat 1 on a Perception check", "The DM uses a voice they can't maintain", "Someone suggests a 'Pincer Maneuver'", "The 'Can I use my reaction?'",
    "A player asks for a discount from a poor merchant", "The 'Wait, I'm resistant to that' realization", "The 'Is the map to scale?' question", "A Nat 20 to jump over a puddle", "The DM sighs and closes their notebook",
    "Someone rolls their dice before the DM asks", "The 'I cast Guidance' for everything", "The 'Did I ever get that gold back?'", "The party argues about the march order", "Finding a mimic that looks like a health potion",
    "The 'I try to pickpocket the guard'", "A player makes a pun that derails the game", "The 'How many hit points do you have?' whisper", "The 'I use my Inspiration'", "The 'Can I use a different skill?' plea",
    "The DM mentions a 2026 update to the rules", "The 'Wait, I have an item for this' discovery", "The 'I check the ceiling' paranoia", "A Nat 1 on a Medicine check makes it worse", "The party successfully avoids the boss fight",
    "The 'Let's just burn the building down' solution", "Someone forgets their character's name", "The DM uses a soundtrack that is too epic for the situation", "The 'Is it my turn?' question", "The 'I rolled a 28, does that hit?' flex"
];