window.BINGO_THEMES = window.BINGO_THEMES || {};
window.BINGO_THEMES["Eurovision"] = [
    "Wind machine", "Fake rain", "Pyrotechnics", "Singer winks at camera", "Rapping segment",
    "Costume change on stage", "Crying performer", "Key change", "Glitter/Confetti", "Fire flames",
    "Traditional instrument", "Opera vocals", "Barefoot performer", "Political message", "Outfit with wings",
    "Flute guy/girl", "Synchronized dancing", "Excessive fog/smoke", "Presenter makes a terrible joke", "Technical difficulty",
    "Awkward green room interview", "12 points to a neighboring country", "0 points received by someone", "Booing from audience", "A ballad about peace",
    "A ballad about love", "Singer falls/trips", "Giant prop on stage", "Folk singing", "Yodeling",
    "Heavy metal band", "Goth/Emo aesthetic", "Silver or gold outfit", "Sequins everywhere", "Singer flying/suspended",
    "Singing in a fake language", "Whistle note", "Someone mentions ABBA", "Host changes outfit", "Spokesperson takes too long",
    "Spokesperson sings the points", "Heart hand gesture", "Playing an invisible instrument", "Singing out of tune", "Excessive makeup",
    "Masked performer", "Glow-in-the-dark elements", "Lasers", "Strobe lights", "Someone brings an animal (or fake animal)",
    "Fiddle playing", "Accordion playing", "Violin solo", "Guitar solo", "Drum solo",
    "Singing in French", "Singing in Italian", "Singing in Spanish", "Bizarre hat", "Capes",
    "Dancers doing flips", "Breakdancing", "Tear-away clothing", "Singer is lifted by dancers", "Camera spins around performer",
    "Someone shouts 'Hello Europe!'", "Someone shouts 'Thank you Europe!'", "Awkward pause before reading points", "Delay in connection with a country", "Presenter mispronounces a name",
    "The 'dark horse' country", "An outfit made of strange materials", "Singing in the rain (fake)", "Piano burning or weird piano", "Singer playing a grand piano",
    "Cheesy choreography", "Performers running on a treadmill", "A giant wheel/hamster wheel", "Twins/Siblings performing", "A returning artist",
    "A song that sounds like an existing pop hit", "Folk dancing", "Someone wearing a traditional costume", "The winner cries", "The winner drops the trophy (or almost)",
    "Crowd singing along loudly", "Flag waving aggressively", "A country gets their first 12 points", "Graham Norton makes a sassy comment (if watching BBC)", "Someone sings entirely in their native language",
    "A dramatic pause in the song", "A capella section", "Beatboxing", "Someone playing the keytar", "A saxophone solo",
    "The LED floor is the main character", "Unnecessary acrobatics", "Stagehands visible in shot",
    "Performer stares into the camera's soul", "Human disco ball outfit", "Shoulder pads wider than the singer",
    "The 'trash bag' look", "Hair held by willpower", "Mid-song costume reveal", "Host tourism ad segment",
    "Host tries to rap or dance", "Performer on phone in green room", "Awkward silence after host joke",
    "Australia mentions the time difference", "The public vote flips the leaderboard", "Sympathetic groan from the crowd",
    "Song about a kitchen appliance", "EDM beat with a folk flute", "Rhyming 'Fire' with 'Desire'",
    "A song with 0% English", "Literal interpretation of lyrics", "The 'Secret' signal/wink",
    "Safety hazard platform shoes", "Spokesperson takes a selfie", "Crowd does the wave",
    "A ballad that lasts 30 seconds too long", "Presenter mentions the 'Spirit of Eurovision'",
    "Someone mentions 1974 or ABBA again", "Graphic glitch on screen", "Singer points to the sky for no reason",
    "Green room delegation too energetic for being at the bottom",
    "Camera cuts to someone eating snacks in the green room",
    "Delegation brings a flag so big it blocks others",
    "Hosts undergo a third costume change", "Painfully scripted 'banter' segment",
    "Postcard video makes a mundane activity look like an epic quest",
    "Host forces a TikTok trend", "Backing vocals are louder than the lead singer",
    "Rhyming 'Tonight' with 'Light' or 'Right'",
    "Lyrics that make zero grammatical sense", "Song ends abruptly on a random dramatic note"
];
